apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ubuntu:18.04
          ports:
            - containerPort: 8080          
          command: ["/bin/bash", "-c", "while true; do echo 'Ejecutando Ubuntu...'; sleep 3600; done"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            privileged: false

